spring:
  datasource:
    password: 12345678
    url: jdbc:mysql://localhost:3306/jpedu?serverTimezone=UTC
    username: root
  jpa:
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      client:
        registration:
         google:
          clientId: 450033227192-o3tpl4terk7qifc93u2vsp6m8frdvvs5.apps.googleusercontent.com
          clientSecret: Llzc1-ADSv7xWs6VZBsDlBF4
          scope:
           - email
           - profile
